//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Номер
    {
        public int Код_номера { get; set; }
        public string Вместимость { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
        public string Статус { get; set; }
    }
}
